version: '3.8'

networks:
  harvey-cloud:
    external: true

services:
  postgres:
    image: postgres:13

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5445:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - harvey-cloud

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "airflow db migrate && airflow users create -u admin -p password -r Admin -e admin@example.com -f admin -l user || true"
    environment:
      &airflow_common_env
      AIRFLOW_UID: 50000
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__RBAC: "True"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
    networks:
      - harvey-cloud
    restart: "no"

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile

    command: airflow scheduler
    environment: *airflow_common_env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - airflow-init
      - postgres
    networks:
      - harvey-cloud

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile

    command: airflow webserver
    ports:
      - "8090:8080"
    environment: *airflow_common_env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - airflow-init
      - postgres
      - airflow-scheduler
    networks:
      - harvey-cloud


volumes:
  pgdata:
