version: '3.8'

networks:
  harvey-cloud:
    external: true

services:
  metabase:
    image: metabase/metabase:v0.55.6
    container_name: listen_brainz_metabase_container

    ports:
      - "3000:3000"

    env_file:
      - .encrypted_env

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - harvey-cloud

volumes:
  db_data:
    driver: local
