"""add gender age country and registered to user

Revision ID: 56905ce790aa
Revises: a5bbd03ec717
Create Date: 2025-07-07 21:40:49.884782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56905ce790aa'
down_revision: Union[str, Sequence[str], None] = 'a5bbd03ec717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.CHAR(length=1), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('registered', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered')
    op.drop_column('users', 'country')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
