#version: '3.8'

networks:
  harvey-cloud:
    external: true

services:
  db_metabase:
    image: postgres:15
    container_name: listen_brainz_db_metabase_container

    ports:
      - "5442:5432"

    env_file:
      - .encrypted_metabase_env

    volumes:
      - db_metabase_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d listen_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    restart: unless-stopped

    networks:
      - harvey-cloud

  db_dm:
    image: postgres:15
    container_name: listen_brainz_db_dm_container

    ports:
      - "5443:5432"

    env_file:
      - .encrypted_dm_env

    volumes:
      - db_dm_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d listen_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    restart: unless-stopped

    networks:
      - harvey-cloud

volumes:
  db_metabase_data:
    driver: local
  db_dm_data:
    driver: local
