version: '3.8'

networks:
  harvey-cloud:
    external: true

services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listen_brainz_spark_master

    environment:
      - SPARK_MODE=master

    volumes:
      - ./app/:/opt/bitnami/spark/app/

    env_file:
      - .encrypted_env

    ports:
      - '8089:8080'
      - '7077:7077'

    networks:
      - harvey-cloud

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listen_brainz_spark_worker

    depends_on:
      - spark-master

    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1

    volumes:
      - ./app/:/opt/bitnami/spark/app/

    env_file:
      - .encrypted_env

    networks:
      - harvey-cloud
